crypto_dbt:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "ODBC Driver 18 for SQL Server"
      server: "{{ env_var('SQL_SERVER_HOST', 'sqlserver') }}"
      database: crypto_data
      schema: dbo
      user: "{{ env_var('SQL_SERVER_USER', 'sa') }}"
      password: "{{ env_var('SQL_SERVER_PASS') }}"
      port: "{{ env_var('SQL_SERVER_PORT', '1433') | int }}"
      threads: 4
      trust_cert: true
      encrypt: false