import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["700"], // bold for nav
  variable: "--font-montserrat",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Crypto Watchlist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-full font-sans bg-gradient-to-br from-black via-purple-900 to-purple-700`}>

        <nav className={`${montserrat.variable} py-8 px-4`}>
          <ul className="max-w-8xl mx-auto flex justify-between items-center">
            <li>
              <a href="/" className="flex items-center gap-2 text-white text-xl font-bold tracking-wide hover:text-purple-300 transition-colors" style={{ fontFamily: "var(--font-montserrat)" }}>
                <img src="/favicon.ico" alt="Logo" className="w-12 h-12"/>
                Crypto Watchlist
              </a>
            </li>
            <li>
              <a href="/add-crypto-form" className="text-white hover:text-gray-300 font-semibold text-2xl" style={{ fontFamily: "var(--font-montserrat)" }}>
                Add Crypto
              </a>
            </li>
          </ul>
        </nav>

        <div className="flex flex-col items-center justify-center min-h-[90vh] w-full">
          {children}
        </div>
        
      </body>
    </html>
  );
}